#-*-coding:utf-8-*-
from selenium import webdriver
import time,os

driver = webdriver.Firefox()
driver.maximize_window()
driver.get('http://172.16.0.23:8013/Index.aspx')
driver.implicitly_wait(30)
time.sleep(1)
driver.find_element_by_id('txtName').clear()
driver.find_element_by_id('txtName').send_keys('admin')
driver.find_element_by_id('txtPassWord').clear()
driver.find_element_by_id('txtPassWord').send_keys('admin')
time.sleep(1)
driver.find_element_by_id('Button1').click()
time.sleep(1)
driver.switch_to.frame(0)
time.sleep(1)
driver.switch_to.default_content()
time.sleep(1)
driver.switch_to.frame(1)
time.sleep(1)
driver.find_element_by_id('imgmenu3').click()
time.sleep(1)
driver.find_element_by_xpath('//a[text()="HIS人员查询"]').click()
time.sleep(1)
driver.switch_to.default_content()
time.sleep(1)
driver.switch_to.frame(2)
time.sleep(1)
driver.find_element_by_id('gv_TPCDataGrid2_ctl03_BtnUpdate').click()

time.sleep(1)
driver.switch_to.frame(0)
print 'OK'
driver.find_element_by_xpath(".//span[@id='lbl_Photo']/following-sibling::input").click()
time.sleep(0.5)
os.system('sc1.exe')
driver.implicitly_wait(10)
driver.find_element_by_id('txt_Motto').send_keys('Good job!')
time.sleep(1)
driver.find_element_by_id('btn_Save').click()
time.sleep(1)
driver.quit()
